using System;
using System.Collections.Generic;

namespace Claims2.DataLayer.Models
{
    public partial class AllBikes3
    {
        public int Id { get; set; }
        public string? Brand { get; set; }
        public string? Name { get; set; }
        public string? NameWithYear { get; set; }
        public int? Year { get; set; }
        public string? RangeName { get; set; }
        public double? Price { get; set; }
        public string? Family { get; set; }
        public string? Sizes { get; set; }
        public string? Colours { get; set; }
        public double? SpecRating { get; set; }
        public double? ValueRating { get; set; }
        public string? Gender { get; set; }
        public string? Age { get; set; }
        public string? FrameType { get; set; }
        public string? ImagePath { get; set; }
        public string? CleanSpecBrakeset { get; set; }
        public string? CleanSpecChainset { get; set; }
        public string? CleanSpecFrontDerailleur { get; set; }
        public string? CleanSpecRearDerailleur { get; set; }
        public string? CleanSpecShifters { get; set; }
        public string? CleanSpecCassette { get; set; }
        public string? CleanSpecFrontFork { get; set; }
        public string? CleanSpecWheels { get; set; }
        public double? OriginalSpecsWheelSize { get; set; }
        public string? OriginalSpecsFrontAxleType { get; set; }
        public string? OriginalSpecsChainsetType { get; set; }
        public string? OriginalSpecsWheelFront { get; set; }
        public string? OriginalSpecsStuntPegs { get; set; }
        public string? OriginalSpecsFrontRim { get; set; }
        public string? OriginalSpecsRearRim { get; set; }
        public string? OriginalSpecsWheelSet { get; set; }
        public string? OriginalSpecsRimTape { get; set; }
        public string? OriginalSpecsHubFront { get; set; }
        public string? OriginalSpecsHubRear { get; set; }
        public string? OriginalSpecsSpokes { get; set; }
        public string? OriginalSpecsTireFront { get; set; }
        public string? OriginalSpecsTireRear { get; set; }
        public string? OriginalSpecsRims { get; set; }
        public string? OriginalSpecsTyreSize { get; set; }
        public string? OriginalSpecsQuickReleaseFrontWheel { get; set; }
        public string? OriginalSpecsQuickReleaseRearWheel { get; set; }
        public string? OriginalSpecsInnerTubes { get; set; }
        public string? OriginalSpecsThroughAxleFront { get; set; }
        public double? OriginalSpecsRimHoles { get; set; }
        public string? OriginalSpecsTyresFrontBack { get; set; }
        public string? OriginalSpecsWheels { get; set; }
        public string? OriginalSpecsChargeTime { get; set; }
        public string? OriginalSpecsMaxSpeed { get; set; }
        public string? OriginalSpecsRange { get; set; }
        public string? OriginalSpecsEngineMotorController { get; set; }
        public string? OriginalSpecsBattery { get; set; }
        public string? OriginalSpecsDisplay { get; set; }
        public string? OriginalSpecsBatteryLockingSystem { get; set; }
        public string? OriginalSpecsChainstayProtection { get; set; }
        public string? OriginalSpecsRearViewMirror { get; set; }
        public string? OriginalSpecsDigitalBatteryCharger { get; set; }
        public string? OriginalSpecsGradientCapability { get; set; }
        public string? OriginalSpecsCharger { get; set; }
        public string? OriginalSpecsWiring { get; set; }
        public string? OriginalSpecsDropoutSensor { get; set; }
        public string? OriginalSpecsLeverSensor { get; set; }
        public string? OriginalSpecsQuickRelease { get; set; }
        public string? OriginalSpecsNipples { get; set; }
        public string? OriginalSpecsHubs { get; set; }
        public string? OriginalSpecsAxleSize { get; set; }
        public string? OriginalSpecsStabilisers { get; set; }
        public string? OriginalSpecsForks { get; set; }
        public string? OriginalSpecsForkTravel { get; set; }
        public string? OriginalSpecsFrontSuspension { get; set; }
        public string? OriginalSpecsRearSuspension { get; set; }
        public string? OriginalSpecsHeadset { get; set; }
        public string? OriginalSpecsHandlebar { get; set; }
        public string? OriginalSpecsStem { get; set; }
        public string? OriginalSpecsGrips { get; set; }
        public string? OriginalSpecsSaddle { get; set; }
        public string? OriginalSpecsSeatPost { get; set; }
        public string? OriginalSpecsBarEnds { get; set; }
        public string? OriginalSpecsBrakeCaliperFront { get; set; }
        public string? OriginalSpecsBrakeCaliperRear { get; set; }
        public string? OriginalSpecsBrakeLeverFront { get; set; }
        public string? OriginalSpecsMudguardsFenders { get; set; }
        public string? OriginalSpecsRackPannierCarrier { get; set; }
        public string? OriginalSpecsTape { get; set; }
        public string? OriginalSpecsBottleCageBosses { get; set; }
        public string? OriginalSpecsSteererSize { get; set; }
        public string? OriginalSpecsCableRouting { get; set; }
        public string? OriginalSpecsBarPads { get; set; }
        public string? OriginalSpecsModuleWeight { get; set; }
        public string? OriginalSpecsSeatReleaseCollar { get; set; }
        public string? OriginalSpecsRigidForks { get; set; }
        public string? OriginalSpecsTopTube { get; set; }
        public string? OriginalSpecsDownTube { get; set; }
        public string? OriginalSpecsRearStays { get; set; }
        public string? OriginalSpecsAerobar { get; set; }
        public string? OriginalSpecsFrontLight { get; set; }
        public string? OriginalSpecsRearLight { get; set; }
        public string? OriginalSpecsFrameLock { get; set; }
        public string? OriginalSpecsHandlebarQuickRelease { get; set; }
        public string? OriginalSpecsLock { get; set; }
        public string? OriginalSpecsLights { get; set; }
        public string? OriginalSpecsBell { get; set; }
        public string? OriginalSpecsExtras { get; set; }
        public string? OriginalSpecsOptions { get; set; }
        public string? OriginalSpecsFramesetAvailable { get; set; }
        public string? OriginalSpecsDynamo { get; set; }
        public string? OriginalSpecsCoatProtector { get; set; }
        public string? OriginalSpecsComponents { get; set; }
        public string? OriginalSpecsWheelRear { get; set; }
        public string? OriginalSpecsCrank { get; set; }
        public string? OriginalSpecsChainringS { get; set; }
        public string? OriginalSpecsBottomBracket { get; set; }
        public string? OriginalSpecsMaxChainringSize { get; set; }
        public string? OriginalSpecsPedals { get; set; }
        public string? OriginalSpecsKickstand { get; set; }
        public string? OriginalSpecsChain { get; set; }
        public string? OriginalSpecsCrankLength { get; set; }
        public string? OriginalSpecsCassetteRearCogs { get; set; }
        public string? OriginalSpecsCassetteRange { get; set; }
        public string? OriginalSpecsAlsoAvailableWithCompactCrank { get; set; }
        public string? OriginalSpecsDrivetrain { get; set; }
        public string? OriginalSpecsBelt { get; set; }
        public string? OriginalSpecsChainTensioner { get; set; }
        public string? OriginalSpecsAlternativeCrankOption { get; set; }
        public string? OriginalSpecsGearInches { get; set; }
        public string? OriginalSpecsFoldingTime { get; set; }
        public string? OriginalSpecsFoldedSize { get; set; }
        public string? OriginalSpecsSuggestedRiderHeight { get; set; }
        public string? OriginalSpecsMaxRiderWeight { get; set; }
        public string? OriginalSpecsClipSystem { get; set; }
        public string? OriginalSpecsLuggageBracket { get; set; }
        public string? OriginalSpecsCablesAndHousing { get; set; }
        public string? OriginalSpecsStandOverHeight { get; set; }
        public string? OriginalSpecsChainGuideGuard { get; set; }
        public string? OriginalSpecsPedalThread { get; set; }
        public string? OriginalSpecsFreewheel { get; set; }
        public string? OriginalSpecsCrankChainringRecommended { get; set; }
        public string? OriginalSpecsFloatingRearDisc { get; set; }
        public double? OriginalSpecsGears { get; set; }
        public string? OriginalSpecsDerailleurFrontMount { get; set; }
        public string? OriginalSpecsGearset { get; set; }
        public string? OriginalSpecsDerailleurFront { get; set; }
        public string? OriginalSpecsDerailleurFrontCableRouteType { get; set; }
        public string? OriginalSpecsDerailleurRear { get; set; }
        public string? OriginalSpecsShifterFrontDerailleur { get; set; }
        public string? OriginalSpecsShifterRearDerailleur { get; set; }
        public string? OriginalSpecsShifterS { get; set; }
        public string? OriginalSpecsBackPedalBrake { get; set; }
        public string? OriginalSpecsHydraulicRimBrakes { get; set; }
        public string? OriginalSpecsMechanicalRimBrakes { get; set; }
        public string? OriginalSpecsGearRatio { get; set; }
        public string? OriginalSpecsBrakeLeverRear { get; set; }
        public string? OriginalSpecsBrakeType { get; set; }
        public string? OriginalSpecsBrakeLevers { get; set; }
        public string? OriginalSpecsGeometry { get; set; }
        public string? OriginalSpecsBrakeCableHousing { get; set; }
        public string? OriginalSpecsDetanglerGyro { get; set; }
        public string? OriginalSpecsBrakeCalipers { get; set; }
        public string? OriginalSpecsFrameCertification { get; set; }
        public string? OriginalSpecsHeadtubeAngle { get; set; }
        public string? OriginalSpecsSeatTubeAngle { get; set; }
        public string? OriginalSpecsTopTubeLength { get; set; }
        public string? OriginalSpecsWaterBottle { get; set; }
        public string? OriginalSpecsWaterBottleBolt { get; set; }
        public string? OriginalSpecsFrontBrakeRotor { get; set; }
        public string? OriginalSpecsRearBrakeRotor { get; set; }
        public string? OriginalSpecsCrosstopLevers { get; set; }
        public string? OriginalSpecsDistanceFromSeatpostToHandlebar { get; set; }
        public string? OriginalSpecsDistanceFromSaddleToPedal { get; set; }
        public string? OriginalSpecsTransmission { get; set; }
        public string? OriginalSpecsMotor { get; set; }
        public string? OriginalSpecsPowerOutput { get; set; }
        public string? OriginalSpecsBrazeOnFittings { get; set; }
        public string? OriginalSpecsBrakeRotor { get; set; }
        public string? OriginalSpecsMechanicalDiscBrakes { get; set; }
        public string? OriginalSpecsHydraulicDiscBrakes { get; set; }
        public string? OriginalSpecsSwingarm { get; set; }
        public string? OriginalSpecsNotes { get; set; }
        public string? OriginalSpecsTyreClearanceMax { get; set; }
        public string? OriginalSpecsDiscReadyHubs { get; set; }
        public string? CleanSpecRearShock { get; set; }
        public string? OriginalSpecsRearTravel { get; set; }
        public string? OriginalSpecsRearShock { get; set; }
        public string? OriginalSpecsHeadTube { get; set; }
        public string? OriginalSpecsRearShockProtector { get; set; }
        public string? OriginalSpecsShockBushingsAndSpacers { get; set; }
        public string? OriginalSpecsRemoteSuspensionSystem { get; set; }
        public string? OriginalSpecsRearShockAdjustableDamping { get; set; }
        public string? OriginalSpecsRearShockLockOut { get; set; }
        public string? OriginalSpecsForksAdjustableDamping { get; set; }
        public string? OriginalSpecsForkLockOut { get; set; }
        public string? OriginalSpecsRearShockSpringOptions { get; set; }
        public string? OriginalSpecsRearSuspensionDesign { get; set; }
        public string? OriginalSpecsRearShockSizeEyeToEye { get; set; }
        public string? OriginalSpecsSuggestedForkTravel { get; set; }
        public string? OriginalSpecsMaxRotorSize { get; set; }
        public string? OriginalSpecsRearShockStroke { get; set; }
        public string? OriginalSpecsThoughAxleRear { get; set; }
        public string? OriginalSpecsReplaceableDerailleurHanger { get; set; }
        public string? OriginalSpecsFrameProtection { get; set; }
        public string? OriginalSpecsAdjustableHeadAngle { get; set; }
        public string? OriginalSpecsAdjustableBottomBracketHeight { get; set; }
        public string? OriginalSpecsFreehubWidthRearWheel { get; set; }
        public string? OriginalSpecsRearRackEyelet { get; set; }
        public string? OriginalSpecsTraditionalMudguardMounts { get; set; }
        public string? OriginalSpecsDropout { get; set; }
        public string? OriginalSpecsMudguardFenderMountRear { get; set; }
        public string? OriginalSpecsForkMaterial { get; set; }
        public string? OriginalSpecsFenderEyelet { get; set; }
        public string? OriginalSpecsDiscReadyFrame { get; set; }
        public string? OriginalSpecsRearDropoutWidth { get; set; }
        public string? OriginalSpecsIscgCompatibleFrame { get; set; }
        public string? OriginalSpecsRearSpacingFrame { get; set; }
        public string? OriginalSpecsDerailleurClampSizeFront { get; set; }
        public string? OriginalSpecsBottomBracketShellDiameter { get; set; }
        public string? OriginalSpecsBottomBracketDropHeight { get; set; }
        public string? OriginalSpecsBottomBracketType { get; set; }
        public string? OriginalSpecsBottomBracketSpindleLength { get; set; }
        public string? OriginalSpecsSeatpostDiameter { get; set; }
        public string? OriginalSpecsBottleCage { get; set; }
        public string? OriginalSpecsUpgrades { get; set; }
        public string? OriginalSpecsSeatpostLength { get; set; }
        public string? OriginalSpecsSeatReleaseCollarDiameter { get; set; }
        public string? OriginalSpecsHeadsetSize { get; set; }
        public string? OriginalSpecsWeight { get; set; }
        public string? OriginalSpecsWeightLbs { get; set; }
        public string? OriginalSpecsForkWeight { get; set; }
        public string? OriginalSpecsHeadsetSpacers { get; set; }
        public string? OriginalSpecsMotorLocation { get; set; }
        public string? OriginalSpecsMotorSize { get; set; }
        public string? OriginalSpecsBatteryCapacity { get; set; }
        public string? OriginalSpecsTechnologies { get; set; }
        public string? OriginalSpecsUse { get; set; }
        public string? OriginalSpecsControls { get; set; }
        public string? OriginalSpecsBasket { get; set; }
        public string? OriginalSpecsFinishingKit { get; set; }
        public string? OriginalSpecsInsideLegLegSize { get; set; }
        public string? OriginalSpecsBrakeset { get; set; }
        public string? OriginalSpecsFrameFit { get; set; }
        public string? OriginalSpecsPartNumber { get; set; }
        public string? OriginalSpecsFrameConstruction { get; set; }
        public string? OriginalSpecsHandlePost { get; set; }
        public string? Chainrings { get; set; }
        public string? Chainset { get; set; }
        public string? FrameMaterial { get; set; }
        public string? FrameMaterialClean { get; set; }
        public string? WheelSize { get; set; }
        public string? ForkTravel { get; set; }
        public string? Gears { get; set; }
        public string? GeometrySize { get; set; }
        public string? GeometryStack { get; set; }
        public string? GeometryReach { get; set; }
        public string? GeometryHeadAngle { get; set; }
        public string? GeometrySeatAngle { get; set; }
        public string? Geometry { get; set; }
    }
}
