using System;
using System.Collections.Generic;

namespace Claims2.DataLayer.Models
{
    public partial class JdsvalidatedItem
    {
        public int Id { get; set; }
        public int ClaimId { get; set; }
        public int ClaimItemId { get; set; }
        public DateTime DateCreated { get; set; }
        public int RefField { get; set; }
        public string? ItemdescriptionField { get; set; }
        public string? ClassgroupField { get; set; }
        public string? Descriptiontype1Field { get; set; }
        public string? Descriptiontype2Field { get; set; }
        public string? Descriptiontype3Field { get; set; }
        public string? GemsetField { get; set; }
        public int? NumgemstotalField { get; set; }
        public string? Group1gemstonetype1Field { get; set; }
        public string? Group1gemstonetype2Field { get; set; }
        public string? Group1gemsizeField { get; set; }
        public string? Metaltype1Field { get; set; }
        public string? QuantumgoldcaratField { get; set; }
        public string? QuantumgrammesField { get; set; }
        public string? RetailpriceField { get; set; }
        public string? Group1gemstotalField { get; set; }
        public string? Group1gemshapeField { get; set; }
        public string? Group1gemcolorclarityField { get; set; }
        public int? Group1gempriceidField { get; set; }
        public string? Group1gemsettingField { get; set; }
        public int? Group2gemstotalField { get; set; }
        public string? Group2gemstonetype1Field { get; set; }
        public string? Group2gemstonetype2Field { get; set; }
        public string? Group2gemshapeField { get; set; }
        public string? Group2gemsizeField { get; set; }
        public string? Group2gemcolorclarityField { get; set; }
        public string? Group2gempriceidField { get; set; }
        public string? Group2gemsettingField { get; set; }
        public int? Group3gemstotalField { get; set; }
        public string? Group3gemstonetype1Field { get; set; }
        public string? Group3gemstonetype2Field { get; set; }
        public string? Group3gemshapeField { get; set; }
        public string? Group3gemsizeField { get; set; }
        public string? Group3gemcolorclarityField { get; set; }
        public double? Group3gempriceidField { get; set; }
        public string? Group3gemsettingField { get; set; }
        public int? Group4gemstotalField { get; set; }
        public string? Group4gemstonetype1Field { get; set; }
        public string? Group4gemstonetype2Field { get; set; }
        public string? Group4gemshapeField { get; set; }
        public string? Group4gemsizeField { get; set; }
        public string? Group4gemcolorclarityField { get; set; }
        public int? Group4gempriceidField { get; set; }
        public string? Group4gemsettingField { get; set; }
        public int? Group5gemstotalField { get; set; }
        public string? Group5gemstonetype1Field { get; set; }
        public string? Group5gemstonetype2Field { get; set; }
        public string? Group5gemshapeField { get; set; }
        public string? Group5gemsizeField { get; set; }
        public string? Group5gemcolorclarityField { get; set; }
        public int? Group5gempriceidField { get; set; }
        public string? Group5gemsettingField { get; set; }
        public string? Group6gemstotalField { get; set; }
        public string? Group6gemstonetype1Field { get; set; }
        public string? Group6gemstonetype2Field { get; set; }
        public string? Group6gemshapeField { get; set; }
        public string? Group6gemsizeField { get; set; }
        public string? Group6gemcolorclarityField { get; set; }
        public string? Group6gempriceidField { get; set; }
        public string? Group6gemsettingField { get; set; }
        public string? Group7gemstotalField { get; set; }
        public string? Group7gemstonetype1Field { get; set; }
        public string? Group7gemstonetype2Field { get; set; }
        public string? Group7gemshapeField { get; set; }
        public string? Group7gemsizeField { get; set; }
        public string? Group7gemcolorclarityField { get; set; }
        public string? Group7gempriceidField { get; set; }
        public string? Group7gemsettingField { get; set; }
        public string? NumberofmetalsField { get; set; }
        public string? Metalsubtype1Field { get; set; }
        public string? Metaltype2Field { get; set; }
        public string? Metalsubtype2Field { get; set; }
        public string? Metaltype3Field { get; set; }
        public string? Metalsubtype3Field { get; set; }
        public string? Metaltype4Field { get; set; }
        public string? Metalsubtype4Field { get; set; }
        public string? Metaltype5Field { get; set; }
        public string? Metalsubtype5Field { get; set; }
        public string? ShapetypeField { get; set; }
        public string? PatternfinishField { get; set; }
        public string? QuantumlengthField { get; set; }
        public string? QuantumwidthField { get; set; }
        public string? QuantumcrosssectionField { get; set; }
        public string? QuantumgraduatedField { get; set; }
        public string? ManufacturetypeField { get; set; }
        public string? GiftedField { get; set; }
        public string? GiftedvalueField { get; set; }
        public string? GiftedbynameField { get; set; }
        public string? GiftedyearField { get; set; }
        public string? GiftedmonthField { get; set; }
        public string? GiftednewusedField { get; set; }
        public string? GiftedcountryField { get; set; }
        public string? PurchasedyearField { get; set; }
        public string? PurchasedmonthField { get; set; }
        public string? PurchasedvendornameField { get; set; }
        public string? PurchasedvendortownField { get; set; }
        public string? PurchasedvendorcountryField { get; set; }
        public string? PurchasedpriceField { get; set; }
        public string? PurchasednewusedField { get; set; }
        public string? PurchasedpriceinflationadjustedField { get; set; }
        public string? PurchasedgotreceiptField { get; set; }
        public string? PurchasedproofacceptedField { get; set; }
        public string? ClaimamountField { get; set; }
        public string? TextnoteField { get; set; }
        public string? AsianshortgotweightField { get; set; }
        public string? AsianshortweightgivenField { get; set; }
        public string? AsianshortweightcalculatedField { get; set; }
        public string? AsianshortgoldqualitypriceField { get; set; }
        public string? AsianshortpurchpriceField { get; set; }
        public string? AsianshortpurchyearField { get; set; }
        public string? AsianshortpurchmonthField { get; set; }
        public string? AsianshortcountryoriginField { get; set; }
        public string? AsianshortgoldfixusedField { get; set; }
        public string? AsianshortstonesetField { get; set; }
        public string? AsianshortgoldcategoryField { get; set; }
        public string? AsianshortweightinputstringField { get; set; }
        public string? AsianshortweightinputunitsField { get; set; }
        public string? AsianshortgrammeweightField { get; set; }
        public string? AsianshortzakatField { get; set; }
        public string? DesignercompanyidField { get; set; }
        public string? DesigneritemrefField { get; set; }
        public string? ItemregistrationnumberField { get; set; }
        public string? ValidationforcedField { get; set; }
        public string? InsurerpriceField { get; set; }
        public string? Username { get; set; }
    }
}
