using System;
using System.Collections.Generic;

namespace Claims2.DataLayer.Models
{
    public partial class NovemberCleansed
    {
        public double? ClaimId { get; set; }
        public string? LossAdjusterAccountRef { get; set; }
        public string? InsCoHandler { get; set; }
        public string? PolicyNumber { get; set; }
        public string? LossAdjusterName { get; set; }
        public string? ReasonForClaim { get; set; }
        public string? CauseOfDamage { get; set; }
        public string? SbsHandler { get; set; }
        public string? LeadItemCommodity { get; set; }
        public string? ClaimAuthorityType { get; set; }
        public string? InsuredSurname { get; set; }
        public string? InsuredPostcode { get; set; }
        public string? HomeTel { get; set; }
        public string? WorkTel { get; set; }
        public string? MobileTel { get; set; }
        public string? Email { get; set; }
        public string? VatRegistered { get; set; }
        public string? InsuranceCo { get; set; }
        public DateTime? DateOpened { get; set; }
        public DateTime? DateClosed { get; set; }
        public string? Commodity { get; set; }
        public string? Peril { get; set; }
        public string? ItemOutcome { get; set; }
        public string? ClaimOutcome { get; set; }
        public string? Supplier { get; set; }
        public double? BuyRate { get; set; }
        public double? CostOfDelivery { get; set; }
        public string? InvDescription { get; set; }
        public double? SaleExVat { get; set; }
        public double? SaleIncVat { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public double? InvoiceNo { get; set; }
        public string? ProductCode { get; set; }
        public double? Quantity { get; set; }
        public double? PoNumber { get; set; }
        public DateTime? OrderPlaced { get; set; }
        public string? ConfirmedBySupplier { get; set; }
        public string? AgreedDeliveryDate { get; set; }
        public string? EstimatedDeliveryDate { get; set; }
        public string? ItemType { get; set; }
        public double? Itemid { get; set; }
        public double? ClaimOrderId { get; set; }
        public string? EngineerName { get; set; }
        public string? Make { get; set; }
        public string? Model { get; set; }
        public DateTime? InstructionBookedOnFnol { get; set; }
        public DateTime? InstructionBookedOnIp { get; set; }
        public string? InstructionBookedOnIpAutomaticly { get; set; }
        public DateTime? FirstContact { get; set; }
        public string? InspectionReadByEngineer { get; set; }
        public string? DateInspectionAcknowledged { get; set; }
        public string? DateRepairread { get; set; }
        public string? HandlerreadPrintedReport { get; set; }
        public string? InspectionCreated { get; set; }
        public string? GoodsRecivedCalloutBooked { get; set; }
        public string? InspectionReported { get; set; }
        public string? Berack { get; set; }
        public string? RepairAuth { get; set; }
        public string? InspCancelled { get; set; }
        public string? RepairComplete { get; set; }
        public string? RepairFailed { get; set; }
        public DateTime? PhoneContactWithPolicyHolder { get; set; }
        public DateTime? SecondContactAttempt { get; set; }
        public DateTime? SecondContactSuccess { get; set; }
        public string? FirstContactLetter { get; set; }
        public string? SecondContactLetter { get; set; }
        public string? ThirdContactLetter { get; set; }
        public string? BiToolUsed { get; set; }
        public string? VariationToInstructionPh { get; set; }
        public string? VariationToInstructionIc { get; set; }
        public string? VariationToInstructionIi { get; set; }
        public string? ExcessCollected { get; set; }
        public string? SmsEmailToPh { get; set; }
        public string? Nondelivery { get; set; }
        public string? InvoiceInterim { get; set; }
        public string? InvoiceFinal { get; set; }
        public DateTime? CloseClaim { get; set; }
        public string? ValidationTool { get; set; }
        public string? CarpetSample { get; set; }
        public string? InspectionReportTo { get; set; }
        public string? QuoteToInsurance { get; set; }
        public string? RecommendRepudiation { get; set; }
        public string? BettermentAgreed { get; set; }
        public string? InstructionToNotRepair { get; set; }
        public string? RepairedItemReturned { get; set; }
        public string? CarpetDryingStarted { get; set; }
        public string? CarpetDryingCompleted { get; set; }
        public string? CarpetVoucherIssued { get; set; }
        public string? CarpetVoucherRedeemed { get; set; }
        public string? ReplacementGoodSordered { get; set; }
        public string? AdditionalGoodSordered { get; set; }
        public string? ClaimItemWithdrawnByPh { get; set; }
        public string? ClaimItemWithdrawnByIc { get; set; }
        public string? ClaimItemRepudiated { get; set; }
        public string? ItemReadyTobeInvoiced { get; set; }
        public string? CashSettledByInsuranceCompany { get; set; }
        public string? CashSettledBySbs { get; set; }
        public string? PurchaseOrderRaised { get; set; }
        public string? AssignOutcome { get; set; }
        public string? DeadOnArrival { get; set; }
        public string? FailedRepair { get; set; }
        public string? CustomerRejectedSettlement { get; set; }
        public string? CancelledDuringTransit { get; set; }
        public string? IncorrectItemSupplied { get; set; }
        public string? AwaitingProofOfPurchase { get; set; }
        public string? InspectionArranged { get; set; }
        public string? EngineerBooked { get; set; }
        public string? CloseItem { get; set; }
        public string? CarpetFitted { get; set; }
        public string? AwaitingFittingDate { get; set; }
        public string? ReplacementFloorOffered { get; set; }
        public string? CleaninProgress { get; set; }
        public string? AwaitingCarpetSample { get; set; }
        public string? SourcingPartsOrMaterialForRepair { get; set; }
        public string? RepairOffered { get; set; }
        public string? VoucherIssued { get; set; }
        public string? RepairToBeCarriedout { get; set; }
        public string? VoucherOffered { get; set; }
        public string? RepairtObecarriedoutGiftware { get; set; }
        public string? SourcingPartsForRepair { get; set; }
        public string? RepairtObecarriedoutJewellry { get; set; }
        public string? RepairtObecarriedoutWatch { get; set; }
        public string? SourcingPartsForRepairJewellry { get; set; }
        public string? MandateSent { get; set; }
        public double? ClaimValue { get; set; }
        public string? LaReference { get; set; }
        public DateTime? TeleSale { get; set; }
        public string? ClaimType { get; set; }
        public string? DpdCollectionDate { get; set; }
        public string? LineItemCategory { get; set; }
        public string? HoursPaused { get; set; }
        public string? LastItemDelDate { get; set; }
        public string? RepairReqSent { get; set; }
        public string? RepairCompleteDate { get; set; }
        public DateTime? ReplacedDate { get; set; }
        public double? MaxTimeToReturnCallInMinutes { get; set; }
        public string? InspectionReportDate { get; set; }
        public string? CustomerInformedOfInspectionResultsDate { get; set; }
        public DateTime? SuccessfulLastContractPriorToGoodsOrdered { get; set; }
        public string? ForTheMonth { get; set; }
        public double? ForTheYear { get; set; }
        public string? Period { get; set; }
        public double? Id { get; set; }
        public double? Laid { get; set; }
    }
}
