using System;
using System.Collections.Generic;

namespace Claims2.DataLayer.Models
{
    public partial class ValuesAcc20141702
    {
        public int? Insuranceclaimid { get; set; }
        public string? Consignment { get; set; }
        public string? LarefS { get; set; }
        public string? LarefC { get; set; }
        public string? AccountRef { get; set; }
        public int? LossadjusterId { get; set; }
        public int? ItemTypeId { get; set; }
        public decimal? Replace11 { get; set; }
        public int? ReplaceItems11 { get; set; }
        public decimal? Repair11 { get; set; }
        public decimal? Inspect11 { get; set; }
        public decimal? Better11 { get; set; }
        public decimal? Excess11 { get; set; }
        public decimal? Credit11 { get; set; }
        public decimal? Carriage11 { get; set; }
        public decimal? SageTotal11 { get; set; }
        public decimal? Total11 { get; set; }
        public decimal? Replace10 { get; set; }
        public int? ReplaceItems10 { get; set; }
        public decimal? Repair10 { get; set; }
        public decimal? Inspect10 { get; set; }
        public decimal? Better10 { get; set; }
        public decimal? Excess10 { get; set; }
        public decimal? Credit10 { get; set; }
        public decimal? Carriage10 { get; set; }
        public decimal? Total10 { get; set; }
        public decimal? SageTotal10 { get; set; }
        public decimal? Replace01 { get; set; }
        public int? ReplaceItems01 { get; set; }
        public decimal? Repair01 { get; set; }
        public decimal? Inspect01 { get; set; }
        public decimal? Better01 { get; set; }
        public decimal? Excess01 { get; set; }
        public decimal? Credit01 { get; set; }
        public decimal? Carriage01 { get; set; }
        public decimal? Total01 { get; set; }
        public decimal? SageTotal01 { get; set; }
        public decimal? Replace02 { get; set; }
        public int? ReplaceItems02 { get; set; }
        public decimal? Repair02 { get; set; }
        public decimal? Inspect02 { get; set; }
        public decimal? Better02 { get; set; }
        public decimal? Excess02 { get; set; }
        public decimal? Credit02 { get; set; }
        public decimal? Carriage02 { get; set; }
        public decimal? Total02 { get; set; }
        public decimal? SageTotal02 { get; set; }
        public decimal? Replace03 { get; set; }
        public int? ReplaceItems03 { get; set; }
        public decimal? Repair03 { get; set; }
        public decimal? Inspect03 { get; set; }
        public decimal? Better03 { get; set; }
        public decimal? Excess03 { get; set; }
        public decimal? Credit03 { get; set; }
        public decimal? Carriage03 { get; set; }
        public decimal? Total03 { get; set; }
        public decimal? SageTotal03 { get; set; }
        public decimal? Replace04 { get; set; }
        public int? ReplaceItems04 { get; set; }
        public decimal? Repair04 { get; set; }
        public decimal? Inspect04 { get; set; }
        public decimal? Better04 { get; set; }
        public decimal? Excess04 { get; set; }
        public decimal? Credit04 { get; set; }
        public decimal? Carriage04 { get; set; }
        public decimal? Total04 { get; set; }
        public decimal? SageTotal04 { get; set; }
        public decimal? Replace05 { get; set; }
        public int? ReplaceItems05 { get; set; }
        public decimal? Repair05 { get; set; }
        public decimal? Inspect05 { get; set; }
        public decimal? Better05 { get; set; }
        public decimal? Excess05 { get; set; }
        public decimal? Credit05 { get; set; }
        public decimal? Carriage05 { get; set; }
        public decimal? Total05 { get; set; }
        public decimal? SageTotal05 { get; set; }
        public decimal? Replace06 { get; set; }
        public int? ReplaceItems06 { get; set; }
        public decimal? Repair06 { get; set; }
        public decimal? Inspect06 { get; set; }
        public decimal? Better06 { get; set; }
        public decimal? Excess06 { get; set; }
        public decimal? Credit06 { get; set; }
        public decimal? Carriage06 { get; set; }
        public decimal? Total06 { get; set; }
        public decimal? SageTotal06 { get; set; }
        public decimal? Replace07 { get; set; }
        public int? ReplaceItems07 { get; set; }
        public decimal? Repair07 { get; set; }
        public decimal? Inspect07 { get; set; }
        public decimal? Better07 { get; set; }
        public decimal? Excess07 { get; set; }
        public decimal? Credit07 { get; set; }
        public decimal? Carriage07 { get; set; }
        public decimal? Total07 { get; set; }
        public decimal? SageTotal07 { get; set; }
        public decimal? Replace08 { get; set; }
        public int? ReplaceItems08 { get; set; }
        public decimal? Repair08 { get; set; }
        public decimal? Inspect08 { get; set; }
        public decimal? Better08 { get; set; }
        public decimal? Excess08 { get; set; }
        public decimal? Credit08 { get; set; }
        public decimal? Carriage08 { get; set; }
        public decimal? Total08 { get; set; }
        public decimal? SageTotal08 { get; set; }
        public decimal? Replace09 { get; set; }
        public int? ReplaceItems09 { get; set; }
        public decimal? Repair09 { get; set; }
        public decimal? Inspect09 { get; set; }
        public decimal? Better09 { get; set; }
        public decimal? Excess09 { get; set; }
        public decimal? Credit09 { get; set; }
        public decimal? Carriage09 { get; set; }
        public decimal? Total09 { get; set; }
        public decimal? SageTotal09 { get; set; }
        public decimal? Replace12 { get; set; }
        public int? ReplaceItems12 { get; set; }
        public decimal? Repair12 { get; set; }
        public decimal? Inspect12 { get; set; }
        public decimal? Better12 { get; set; }
        public decimal? Excess12 { get; set; }
        public decimal? Credit12 { get; set; }
        public decimal? Carriage12 { get; set; }
        public decimal? Total12 { get; set; }
        public decimal? SageTotal12 { get; set; }
    }
}
